<?php include_once('./includes/header.php'); ?>
<body class="page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo page-md">

<?php include_once('./includes/admin_panel.php'); ?>

<div class="clearfix"> </div><div class="page-container">

<?php include_once('./includes/sidebar.php'); ?>
 <div class="page-content-wrapper">

        <div class="page-content" style="min-height: 567px;">

            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green">
                        <i class="icon-user font-green"></i>
                        <span class="caption-subject bold uppercase">Users</span>
                    </div>
                    <div class="actions">
                        <div class="btn-group btn-group-devided">
                            <a href="./add_user.php" class="btn green btn-outline" > Create User <i class="fa fa-plus"></i>
                            </a>

                            <a href="#" class="btn green btn-outline"> Export CSV <i class="fa fa-file-excel-o"></i>
                            </a>

                        </div>
                    </div>

                </div>

                <div class="portlet-body">
                        <div id="userTable_wrapper" class="dataTables_wrapper no-footer"><div class="row"><div class="col-md-6 col-sm-6"><div class="dataTables_length" id="userTable_length"><label> <select name="userTable_length" aria-controls="userTable" class="form-control input-sm input-xsmall input-inline"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> records </label></div></div><div class="col-md-6 col-sm-6"><div id="userTable_filter" class="dataTables_filter"><label>Search:<input type="search" class="form-control input-sm input-small input-inline" placeholder="" aria-controls="userTable"></label></div></div><div id="userTable_processing" class="dataTables_processing" style="display: none;">Processing...</div></div><div class="table-scrollable"><table class="table table-striped table-bordered table-hover dt-responsive dataTable no-footer dtr-inline collapsed" id="userTable" role="grid" aria-describedby="userTable_info" style="width: 949px;">
                            <thead>
                            <tr role="row"><th class="sorting_desc" tabindex="0" aria-controls="userTable" rowspan="1" colspan="1" style="width: 29px;" aria-sort="descending" aria-label="Id: activate to sort column ascending">Id</th><th class="min-tablet sorting" tabindex="0" aria-controls="userTable" rowspan="1" colspan="1" style="width: 151px;" aria-label="Name: activate to sort column ascending">Name</th><th style="width: 98px;" class="min-tablet sorting" tabindex="0" aria-controls="userTable" rowspan="1" colspan="1" aria-label="Avatar: activate to sort column ascending">Avatar</th><th class="min-phone-l sorting" tabindex="0" aria-controls="userTable" rowspan="1" colspan="1" style="width: 99px;" aria-label="Username: activate to sort column ascending">Username</th><th class="sorting" tabindex="0" aria-controls="userTable" rowspan="1" colspan="1" style="width: 210px;" aria-label="Email: activate to sort column ascending">Email</th><th class="min-tablet sorting" tabindex="0" aria-controls="userTable" rowspan="1" colspan="1" style="width: 68px;" aria-label="Status: activate to sort column ascending">Status</th><th class="sorting_disabled" rowspan="1" colspan="1" style="width: 0px; " aria-label="Actions">Actions</th></tr>
                            </thead>

                        <tbody><tr role="row" class="odd" id="user_<a type=&quot;button&quot; href=&quot;javascript:;&quot; onclick=&quot;editModal(21)&quot; class=&quot;btn btn green btn-outline btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-edit&quot;></i> Edit</a>&amp;nbsp;
                <a href=&quot;javascript:;&quot; onclick=&quot;del(21,'Marina Hartmann')&quot; class=&quot;btn btn-outline red btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-trash-o&quot;></i> Delete</a>"><td class="sorting_1" tabindex="0">21</td><td>Marina Hartmann</td><td><img style="width:9em ;height:8em;" src="./assets/images/a6.jpg"></td><td>zena</td><td>maybell.kunze@ullrich.org</td><td><span class="label label-danger">Inactive</span></td><td ><a type="button" href="javascript:;" onclick="editModal(21)" class="btn btn green btn-outline btn-xs margin-top-10">	<i class="fa fa-edit"></i> Edit</a>&nbsp;
                <a href="javascript:;" onclick="del(21,'Marina Hartmann')" class="btn btn-outline red btn-xs margin-top-10">	<i class="fa fa-trash-o"></i> Delete</a></td></tr><tr role="row" class="even" id="user_<a type=&quot;button&quot; href=&quot;javascript:;&quot; onclick=&quot;editModal(20)&quot; class=&quot;btn btn green btn-outline btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-edit&quot;></i> Edit</a>&amp;nbsp;
                <a href=&quot;javascript:;&quot; onclick=&quot;del(20,'Dr. Lenna Hills V')&quot; class=&quot;btn btn-outline red btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-trash-o&quot;></i> Delete</a>"><td class="sorting_1" tabindex="0">20</td><td>Dr. Lenna Hills V</td><td><img style="width:9em ;height:8em;" src="./assets/images/a5.jpg"></td><td>earlene</td><td>ddaniel@hotmail.com</td><td><span class="label label-success">Active</span></td><td ><a type="button" href="javascript:;" onclick="editModal(20)" class="btn btn green btn-outline btn-xs margin-top-10">	<i class="fa fa-edit"></i> Edit</a>&nbsp;
                <a href="javascript:;" onclick="del(20,'Dr. Lenna Hills V')" class="btn btn-outline red btn-xs margin-top-10">	<i class="fa fa-trash-o"></i> Delete</a></td></tr><tr role="row" class="odd" id="user_<a type=&quot;button&quot; href=&quot;javascript:;&quot; onclick=&quot;editModal(19)&quot; class=&quot;btn btn green btn-outline btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-edit&quot;></i> Edit</a>&amp;nbsp;
                <a href=&quot;javascript:;&quot; onclick=&quot;del(19,'Mylene Goodwin')&quot; class=&quot;btn btn-outline red btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-trash-o&quot;></i> Delete</a>"><td class="sorting_1" tabindex="0">19</td><td>Mylene Goodwin</td><td><img style="width:9em ;height:8em;" src="./assets/images/a4.jpg"></td><td>mathias</td><td>kblanda@schneider.com</td><td><span class="label label-success">Active</span></td><td ><a type="button" href="javascript:;" onclick="editModal(19)" class="btn btn green btn-outline btn-xs margin-top-10">	<i class="fa fa-edit"></i> Edit</a>&nbsp;
                <a href="javascript:;" onclick="del(19,'Mylene Goodwin')" class="btn btn-outline red btn-xs margin-top-10">	<i class="fa fa-trash-o"></i> Delete</a></td></tr><tr role="row" class="even" id="user_<a type=&quot;button&quot; href=&quot;javascript:;&quot; onclick=&quot;editModal(18)&quot; class=&quot;btn btn green btn-outline btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-edit&quot;></i> Edit</a>&amp;nbsp;
                <a href=&quot;javascript:;&quot; onclick=&quot;del(18,'Cassidy Jacobs')&quot; class=&quot;btn btn-outline red btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-trash-o&quot;></i> Delete</a>"><td class="sorting_1" tabindex="0">18</td><td>Cassidy Jacobs</td><td><img style="width:9em ;height:8em;" src="./assets/images/a3.jpg"></td><td>noemie</td><td>stephen17@yahoo.com</td><td><span class="label label-success">Active</span></td><td ><a type="button" href="javascript:;" onclick="editModal(18)" class="btn btn green btn-outline btn-xs margin-top-10">	<i class="fa fa-edit"></i> Edit</a>&nbsp;
                <a href="javascript:;" onclick="del(18,'Cassidy Jacobs')" class="btn btn-outline red btn-xs margin-top-10">	<i class="fa fa-trash-o"></i> Delete</a></td></tr><tr role="row" class="odd" id="user_<a type=&quot;button&quot; href=&quot;javascript:;&quot; onclick=&quot;editModal(17)&quot; class=&quot;btn btn green btn-outline btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-edit&quot;></i> Edit</a>&amp;nbsp;
                <a href=&quot;javascript:;&quot; onclick=&quot;del(17,'Lew Powlowski DVM')&quot; class=&quot;btn btn-outline red btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-trash-o&quot;></i> Delete</a>"><td class="sorting_1" tabindex="0">17</td><td>Lew Powlowski DVM</td><td><img style="width:9em ;height:8em;" src="./assets/images/a2.jpg"></td><td>mellie</td><td>wwalker@gmail.com</td><td><span class="label label-success">Active</span></td><td ><a type="button" href="javascript:;" onclick="editModal(17)" class="btn btn green btn-outline btn-xs margin-top-10">	<i class="fa fa-edit"></i> Edit</a>&nbsp;
                <a href="javascript:;" onclick="del(17,'Lew Powlowski DVM')" class="btn btn-outline red btn-xs margin-top-10">	<i class="fa fa-trash-o"></i> Delete</a></td></tr><tr role="row" class="even" id="user_<a type=&quot;button&quot; href=&quot;javascript:;&quot; onclick=&quot;editModal(16)&quot; class=&quot;btn btn green btn-outline btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-edit&quot;></i> Edit</a>&amp;nbsp;
                <a href=&quot;javascript:;&quot; onclick=&quot;del(16,'Khalid Dibbert')&quot; class=&quot;btn btn-outline red btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-trash-o&quot;></i> Delete</a>"><td class="sorting_1" tabindex="0">16</td><td>Khalid Dibbert</td><td><img style="width:9em ;height:8em;" src="./assets/images/a1.jpg"></td><td>kaela</td><td>hayes.christa@hotmail.com</td><td><span class="label label-danger">Inactive</span></td><td ><a type="button" href="javascript:;" onclick="editModal(16)" class="btn btn green btn-outline btn-xs margin-top-10">	<i class="fa fa-edit"></i> Edit</a>&nbsp;
                <a href="javascript:;" onclick="del(16,'Khalid Dibbert')" class="btn btn-outline red btn-xs margin-top-10">	<i class="fa fa-trash-o"></i> Delete</a></td></tr><tr role="row" class="odd" id="user_<a type=&quot;button&quot; href=&quot;javascript:;&quot; onclick=&quot;editModal(15)&quot; class=&quot;btn btn green btn-outline btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-edit&quot;></i> Edit</a>&amp;nbsp;
                <a href=&quot;javascript:;&quot; onclick=&quot;del(15,'Louvenia Rosenbaum')&quot; class=&quot;btn btn-outline red btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-trash-o&quot;></i> Delete</a>"><td class="sorting_1" tabindex="0">15</td><td>Louvenia Rosenbaum</td><td><img style="width:9em ;height:8em;" src="./assets/images/a0.jpg"></td><td>nat</td><td>abagail24@gmail.com</td><td><span class="label label-danger">Inactive</span></td><td ><a type="button" href="javascript:;" onclick="editModal(15)" class="btn btn green btn-outline btn-xs margin-top-10">	<i class="fa fa-edit"></i> Edit</a>&nbsp;
                <a href="javascript:;" onclick="del(15,'Louvenia Rosenbaum')" class="btn btn-outline red btn-xs margin-top-10">	<i class="fa fa-trash-o"></i> Delete</a></td></tr><tr role="row" class="even" id="user_<a type=&quot;button&quot; href=&quot;javascript:;&quot; onclick=&quot;editModal(14)&quot; class=&quot;btn btn green btn-outline btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-edit&quot;></i> Edit</a>&amp;nbsp;
                <a href=&quot;javascript:;&quot; onclick=&quot;del(14,'Titus Mayert')&quot; class=&quot;btn btn-outline red btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-trash-o&quot;></i> Delete</a>"><td class="sorting_1" tabindex="0">14</td><td>Titus Mayert</td><td><img style="width:9em ;height:8em;" src="./assets/images/a13.jpg"></td><td>vernice</td><td>dietrich.valentine@gmail.com</td><td><span class="label label-success">Active</span></td><td ><a type="button" href="javascript:;" onclick="editModal(14)" class="btn btn green btn-outline btn-xs margin-top-10">	<i class="fa fa-edit"></i> Edit</a>&nbsp;
                <a href="javascript:;" onclick="del(14,'Titus Mayert')" class="btn btn-outline red btn-xs margin-top-10">	<i class="fa fa-trash-o"></i> Delete</a></td></tr><tr role="row" class="odd" id="user_<a type=&quot;button&quot; href=&quot;javascript:;&quot; onclick=&quot;editModal(13)&quot; class=&quot;btn btn green btn-outline btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-edit&quot;></i> Edit</a>&amp;nbsp;
                <a href=&quot;javascript:;&quot; onclick=&quot;del(13,'Dawson Lind')&quot; class=&quot;btn btn-outline red btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-trash-o&quot;></i> Delete</a>"><td class="sorting_1" tabindex="0">13</td><td>Dawson Lind</td><td><img style="width:9em ;height:8em;" src="./assets/images/a12.jpg"></td><td>cornell</td><td>joany36@hotmail.com</td><td><span class="label label-success">Active</span></td><td ><a type="button" href="javascript:;" onclick="editModal(13)" class="btn btn green btn-outline btn-xs margin-top-10">	<i class="fa fa-edit"></i> Edit</a>&nbsp;
                <a href="javascript:;" onclick="del(13,'Dawson Lind')" class="btn btn-outline red btn-xs margin-top-10">	<i class="fa fa-trash-o"></i> Delete</a></td></tr><tr role="row" class="even" id="user_<a type=&quot;button&quot; href=&quot;javascript:;&quot; onclick=&quot;editModal(12)&quot; class=&quot;btn btn green btn-outline btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-edit&quot;></i> Edit</a>&amp;nbsp;
                <a href=&quot;javascript:;&quot; onclick=&quot;del(12,'Scot Torp')&quot; class=&quot;btn btn-outline red btn-xs margin-top-10&quot;>	<i class=&quot;fa fa-trash-o&quot;></i> Delete</a>"><td class="sorting_1" tabindex="0">12</td><td>Scot Torp</td><td><img style="width:9em ;height:8em;" src="./assets/images/a11.jpg"></td><td>hadley</td><td>mariana94@lehner.com</td><td><span class="label label-success">Active</span></td><td ><a type="button" href="javascript:;" onclick="editModal(12)" class="btn btn green btn-outline btn-xs margin-top-10">	<i class="fa fa-edit"></i> Edit</a>&nbsp;
                <a href="javascript:;" onclick="del(12,'Scot Torp')" class="btn btn-outline red btn-xs margin-top-10">	<i class="fa fa-trash-o"></i> Delete</a></td></tr></tbody></table></div><div class="row"><div class="col-md-5 col-sm-5">
                    <div class="dataTables_info" id="userTable_info" role="status" aria-live="polite">Showing 1 to 10 of 21 entries (filtered from 11 total entries)</div></div><div class="col-md-7 col-sm-7"><div class="dataTables_paginate paging_bootstrap_number" id="userTable_paginate"><ul class="pagination" style="visibility: visible;"><li class="prev disabled"><a href="#" title="Prev"><i class="fa fa-angle-left"></i></a></li><li class="active"><a href="#">1</a></li><li><a href="#">2</a></li><li><a href="#">3</a></li><li class="next"><a href="#" title="Next"><i class="fa fa-angle-right"></i></a></li></ul></div></div></div></div>
                            <!-- /.table-responsive -->
                    </div>
                    <!-- /.portlet -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#content-container -->
    </div>
<?php include_once('./includes/footer.php'); ?>
